apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opossum
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/opossum
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  kubeConfig:
    secretRef:
      name: opossum-kubeconfig
